alias: COMI-Entre-conjuntos

generate-output: true
solution: solution/solution.cpp
timeout: 0.5
admin-groups: [workshop-2017]

params:
  title: Entre conjuntos
  source: Curso COMI

  visibility: 1

  # valid options: all, karel
  languages: all

  time_limit: 1000
  memory_limit: 32768
  output_limit: 16384
  stack_limit: 10485760

  overall_wall_time_limit: 60000

  # valid options: token-caseless, token-numeric, token-numeric, custom, literal
  validator: token-caseless
  validator_time_limit: 1000
  extra_wall_time: 0

  email_clarifications: 0
