alias: COMI-Permutaciones

generate-output: true
solution: solutions/100_A.cpp
timeout: 1.5
admin-groups: [workshop-2017]
params:
  title: Permutaciones salvajes
  source: Curso OMI (Orac)

  visibility: 1

  languages: all

  time_limit: 2500
  memory_limit: 32768
  output_limit: 16384
  stack_limit: 10485760

  overall_wall_time_limit: 60000

  validator: token-caseless
  validator_time_limit: 1000
  extra_wall_time: 0

  email_clarifications: 0
