alias: COMI-Cola-Interactivo

admin-groups: [workshop-2017]

generate-output: false

interactive: true

params:
  title: Cola Interactivo
  source: Curso OMI

  visibility: 1

  languages: all

  time_limit: 1000
  memory_limit: 32768
  output_limit: 16384
  stack_limit: 10485760

  overall_wall_time_limit: 60000

  validator: token-caseless
  validator_time_limit: 1000
  extra_wall_time: 1000

  email_clarifications: 0
